blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView
)
from . import views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='blog-about'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name="register-page"),
    path('profile/', user_views.profile, name="profile"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('password-reset/', 
        auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name="password_reset"),
    path('password-reset/done/', 
        auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name="password_reset_confirm"),
    path('',include('blog.urls')),
]
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from . import views
app_name='polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
# ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
# ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def __str__(self):
		return self.question_text
class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text
class TrueFalse(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	tf_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.tf_text

polls/views.py
from django.shortcuts import render
from django.http import Http404
from django.http import HttpResponse
from .models import Question
# Create your views here.
def index(request):
	context={'latest_question_list':Question.objects.order_by('-pub_date')[:5]}
	return render(request, 'polls/index.html',context)

def tf(request):
	context={'latest_question_list':Question.objects.order_by('-pub_date')[:5]}
	return render(request, 'polls/tf_index.html',context)

def detail(request, question_id):
	try:
		question = Question.objects.get(pk=question_id)
	except Question.DoesNotExist:
		raise Http404("Question does not exist")
	return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
	response = "You're looking at the results of question %s."
	return HttpResponse(response % question_id)


def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
		return render(request, 'polls/detail.html', {'question': question,'error_message': "You didn't select a choice.",})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		# Always return an HttpResponseRedirect after successfully dealing
		# with POST data. This prevents data from being posted twice if a
		# user hits the Back button.
		return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

templates/polls/detail.html
{% extends "blog/base.html" %}
{% load i18n %}
{% block content %}
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <h5 class="mr-2" class="article-title">{{ question.question_text}}</h5>
        <br>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <form action="{% url 'polls:vote' question.id %}" method="post">
        	{% csrf_token %}
        	{% for choice in question.choice_set.all %}
        	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id }}">
        	<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>{% endfor %}
        	<input type="submit" value="Vote">
        </form>
        <small class="text-muted">{{ question.pub_date|date:"F d, Y" }}</small>
        
      </div>
    </div>
  </article>
{% endblock content %}

templates/polls/index.html
{% extends "blog/base.html" %}
{% load i18n %}
{% block content %}
    <div class="content-section">
    {% if latest_question_list %}
    <ul>
      {% for question in latest_question_list %}
      <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
         {% endfor %}
    </ul>
    {% else %}
     <p>No polls are available.</p>
    {% endif %}
    </div>
{% endblock content %}

templates/polls/tf_detail.html
{% extends "blog/base.html" %}
{% load i18n %}
{% block content %}
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <h5 class="mr-2" class="article-title">{{ question.question_text}}</h5>
        {% for tf in question.truefalse_set.all %}
        <li>{{ tf.tf_text }}</li>
        {% endfor %}
        <small class="text-muted">{{ question.pub_date|date:"F d, Y" }}</small>
        
      </div>
    </div>
  </article>
{% endblock content %}

templates/polls/tf_index.html
{% extends "blog/base.html" %}
{% load i18n %}
{% block content %}
    <div class="content-section">
    {% if latest_question_list %}
    <ul>
      {% for question in latest_question_list %}
      <li><a href="{% url 'tf_detail' question.id %}">{{ question.question_text }}</a></li>
         {% endfor %}
    </ul>
    {% else %}
     <p>No polls are available.</p>
    {% endif %}
    </div>
{% endblock content %}